using System.Globalization;

namespace TPMQoLTrainer;

internal sealed record LanguageInfo(string Code, string Name);

internal static class L
{
    internal static readonly LanguageInfo[] Languages =
    {
        new("en", "English"),
        new("fr", "Français"),
        new("it", "Italiano"),
        new("de", "Deutsch"),
        new("es-ES", "Español (España)"),
        new("ja", "日本語"),
        new("ko", "한국어"),
        new("pt-BR", "Português (Brasil)"),
        new("zh-CN", "简体中文"),
        new("zh-TW", "繁體中文"),
        new("tr", "Türkçe"),
        new("pl", "Polski"),
        new("ru", "Русский"),
        new("es-419", "Español (Latinoamérica)"),
        new("th", "ไทย")
    };

    private static readonly Dictionary<string, Dictionary<string, string>> Data =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new()
            {
                ["language"] = "Language",
                ["choose_config"] = "Choose config…",
                ["game_running"] = "Game running",
                ["game_stopped"] = "Game not running",
                ["saved_live"] = "Saved · live reload active",
                ["saved_stopped"] = "Saved · game not running",
                ["mod"] = "Mod",
                ["speed"] = "Speed",
                ["workshop"] = "Workshop jobs",
                ["training"] = "Training duration",
                ["analysis"] = "Analysis duration",
                ["vet"] = "Veterinary treatment",
                ["expeditions"] = "Expedition duration",
                ["staff"] = "Staff movement",
                ["exhibit_extra_speed"] = "Install exhibit extras",
                ["knowledge"] = "Knowledge",
                ["analysis_max"] = "Exhibits: max knowledge after 1 analysis",
                ["vet_max"] = "Animals / fish / ghosts: max knowledge after 1 treatment",
                ["applicants"] = "Applicants",
                ["minimum_rank"] = "Minimum level for new applicants",
                ["base_skill"] = "Keep 1 vanilla base skill; leave remaining skill slots free",
                ["max_survey"] = "Fully survey the area after 1 expedition",
                ["min_quality"] = "Minimum quality of expedition finds",
                ["force_quality"] = "Force all finds to exactly this quality",
                ["security"] = "Security",
                ["coverage_radius"] = "Security room / camera coverage radius",
                ["health"] = "Health",
                ["first_aid"] = "First aid cures expedition illnesses without a workshop part",
                ["preservation"] = "Preservation / no deterioration",
                ["preserve_exhibits"] = "Exhibits: condition stays at 100%",
                ["immortal_plants"] = "Botany exhibits: life stays at 100%",
                ["aquariums_clean"] = "Aquariums: stay clean + filter capacity 999",
                ["apply"] = "Apply",
                ["reload"] = "Reload",
                ["vanilla"] = "All vanilla",
                ["start_game"] = "Start game",
                ["footer"] = "Changes are written to the existing BepInEx config and applied live by the mod.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normal",
                ["q_great"] = "Great",
                ["q_epic"] = "Epic",
                ["q_pristine"] = "Pristine",
                ["setup_close_game"] = "Two Point Museum must be closed to finish installation or update. Close the game, then click Retry.",
                ["setup_failed"] = "Automatic installation failed",
                ["select_game_folder"] = "Select the Two Point Museum game folder (the folder containing TPM.exe).",
                ["invalid_game_folder"] = "This is not a valid Two Point Museum game folder.",
                ["config_missing"] = "TPMQoL.cfg was not found. Please choose the config file manually.",
                ["load_error"] = "Config could not be loaded",
                ["save_error"] = "Config could not be saved",
                ["start_error"] = "Game could not be started"
            },
            ["de"] = new()
            {
                ["language"] = "Sprache",
                ["choose_config"] = "Config wählen…",
                ["game_running"] = "Spiel läuft",
                ["game_stopped"] = "Spiel nicht gestartet",
                ["saved_live"] = "Gespeichert · Hot-Reload aktiv",
                ["saved_stopped"] = "Gespeichert · Spiel nicht gestartet",
                ["mod"] = "Mod",
                ["speed"] = "Geschwindigkeit",
                ["workshop"] = "Werkstatt-Arbeiten",
                ["training"] = "Training-Dauer",
                ["analysis"] = "Analyse-Dauer",
                ["vet"] = "Tierarzt-Behandlung",
                ["expeditions"] = "Expeditionsdauer",
                ["staff"] = "Mitarbeiter-Bewegung",
                ["exhibit_extra_speed"] = "Exponat-Extras installieren",
                ["knowledge"] = "Wissen",
                ["analysis_max"] = "Exponate: nach 1 Analyse maximales Wissen",
                ["vet_max"] = "Tiere / Fische / Geister: nach 1 Behandlung maximales Wissen",
                ["applicants"] = "Bewerber",
                ["minimum_rank"] = "Mindestlevel neuer Bewerber",
                ["base_skill"] = "1 Vanilla-Basisskill behalten; übrige Skillplätze frei",
                ["max_survey"] = "Gebiet nach 1 Expedition vollständig erkundet",
                ["min_quality"] = "Mindestqualität der Expeditionsfunde",
                ["force_quality"] = "Funde immer exakt auf diese Qualität setzen",
                ["security"] = "Sicherheit",
                ["coverage_radius"] = "Überwachungsraum- / Kamera-Reichweite",
                ["health"] = "Gesundheit",
                ["first_aid"] = "Verbandskasten heilt Expeditionskrankheiten ohne Werkstattteil",
                ["preservation"] = "Erhaltung / kein Verfall",
                ["preserve_exhibits"] = "Exponate: Zustand bleibt 100 %",
                ["immortal_plants"] = "Botanik-Exponate: Leben bleibt 100 %",
                ["aquariums_clean"] = "Aquarien: sauber + Filterkapazität 999",
                ["apply"] = "Übernehmen",
                ["reload"] = "Neu laden",
                ["vanilla"] = "Alles Vanilla",
                ["start_game"] = "Spiel starten",
                ["footer"] = "Änderungen werden in die bestehende BepInEx-Config geschrieben und vom Mod live übernommen.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normal",
                ["q_great"] = "Grossartig",
                ["q_epic"] = "Episch",
                ["q_pristine"] = "Makellos",
                ["setup_close_game"] = "Two Point Museum muss für die Installation oder das Update geschlossen sein. Schliesse das Spiel und klicke danach auf Wiederholen.",
                ["setup_failed"] = "Automatische Installation fehlgeschlagen",
                ["select_game_folder"] = "Wähle den Two-Point-Museum-Spielordner aus (den Ordner mit TPM.exe).",
                ["invalid_game_folder"] = "Dieser Ordner ist keine gültige Two-Point-Museum-Installation.",
                ["config_missing"] = "TPMQoL.cfg wurde nicht gefunden. Bitte wähle die Config-Datei manuell.",
                ["load_error"] = "Config konnte nicht geladen werden",
                ["save_error"] = "Config konnte nicht gespeichert werden",
                ["start_error"] = "Spiel konnte nicht gestartet werden"
            },
            ["fr"] = new()
            {
                ["language"] = "Langue",
                ["choose_config"] = "Choisir la config…",
                ["game_running"] = "Jeu en cours",
                ["game_stopped"] = "Jeu non lancé",
                ["saved_live"] = "Enregistré · rechargement à chaud actif",
                ["saved_stopped"] = "Enregistré · jeu non lancé",
                ["mod"] = "Mod",
                ["speed"] = "Vitesse",
                ["workshop"] = "Atelier",
                ["training"] = "Formation",
                ["analysis"] = "Analyse",
                ["vet"] = "Vétérinaire",
                ["expeditions"] = "Expéditions",
                ["staff"] = "Personnel",
                ["exhibit_extra_speed"] = "Extras d'exposition",
                ["knowledge"] = "Connaissances",
                ["analysis_max"] = "Analyse : connaissances max après une analyse",
                ["vet_max"] = "Vétérinaire : connaissances max après un traitement",
                ["applicants"] = "Candidats",
                ["minimum_rank"] = "Rang minimum",
                ["base_skill"] = "Conserver la compétence de base vanilla, supprimer les compétences aléatoires supplémentaires",
                ["max_survey"] = "Exploration max après une expédition",
                ["min_quality"] = "Qualité minimale",
                ["force_quality"] = "Forcer la qualité exacte",
                ["security"] = "Sécurité",
                ["coverage_radius"] = "Rayon de couverture",
                ["health"] = "Santé",
                ["first_aid"] = "Les premiers secours soignent les maladies d'expédition",
                ["preservation"] = "Préservation des expositions",
                ["preserve_exhibits"] = "Expositions : état maintenu à 100 %",
                ["immortal_plants"] = "Botanique : vie maintenue à 100 %",
                ["aquariums_clean"] = "Aquariums : propres + filtre 999",
                ["apply"] = "Appliquer",
                ["reload"] = "Recharger",
                ["vanilla"] = "Tout en vanilla",
                ["start_game"] = "Lancer le jeu",
                ["footer"] = "Les modifications sont écrites dans la config BepInEx existante et appliquées en direct par le mod.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normale",
                ["q_great"] = "Excellente",
                ["q_epic"] = "Épique",
                ["q_pristine"] = "Impeccable",
                ["config_missing"] = "TPMQoL.cfg est introuvable. Veuillez sélectionner le fichier de configuration manuellement.",
                ["load_error"] = "Impossible de charger la configuration",
                ["save_error"] = "Impossible d'enregistrer la configuration",
                ["start_error"] = "Impossible de lancer le jeu"
            },
            ["it"] = new()
            {
                ["language"] = "Lingua",
                ["choose_config"] = "Scegli config…",
                ["game_running"] = "Gioco in esecuzione",
                ["game_stopped"] = "Gioco non avviato",
                ["saved_live"] = "Salvato · ricaricamento live attivo",
                ["saved_stopped"] = "Salvato · gioco non avviato",
                ["mod"] = "Mod",
                ["speed"] = "Velocità",
                ["workshop"] = "Officina",
                ["training"] = "Formazione",
                ["analysis"] = "Analisi",
                ["vet"] = "Veterinario",
                ["expeditions"] = "Spedizioni",
                ["staff"] = "Personale",
                ["exhibit_extra_speed"] = "Extra dell'esposizione",
                ["knowledge"] = "Conoscenza",
                ["analysis_max"] = "Analisi: conoscenza massima dopo un'analisi",
                ["vet_max"] = "Veterinario: conoscenza massima dopo un trattamento",
                ["applicants"] = "Candidati",
                ["minimum_rank"] = "Grado minimo",
                ["base_skill"] = "Mantieni l'abilità base vanilla, rimuovi le abilità casuali aggiuntive",
                ["max_survey"] = "Esplorazione massima dopo una spedizione",
                ["min_quality"] = "Qualità minima",
                ["force_quality"] = "Forza qualità esatta",
                ["security"] = "Sicurezza",
                ["coverage_radius"] = "Raggio di copertura",
                ["health"] = "Salute",
                ["first_aid"] = "Il primo soccorso cura le malattie da spedizione",
                ["preservation"] = "Conservazione delle esposizioni",
                ["preserve_exhibits"] = "Esposizioni: stato sempre al 100%",
                ["immortal_plants"] = "Botanica: vita sempre al 100%",
                ["aquariums_clean"] = "Acquari: puliti + filtro 999",
                ["apply"] = "Applica",
                ["reload"] = "Ricarica",
                ["vanilla"] = "Tutto vanilla",
                ["start_game"] = "Avvia gioco",
                ["footer"] = "Le modifiche vengono scritte nella config BepInEx esistente e applicate in tempo reale dal mod.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normale",
                ["q_great"] = "Ottima",
                ["q_epic"] = "Epica",
                ["q_pristine"] = "Immacolata",
                ["config_missing"] = "TPMQoL.cfg non è stato trovato. Seleziona manualmente il file di configurazione.",
                ["load_error"] = "Impossibile caricare la configurazione",
                ["save_error"] = "Impossibile salvare la configurazione",
                ["start_error"] = "Impossibile avviare il gioco"
            },
            ["es-ES"] = new()
            {
                ["language"] = "Idioma",
                ["choose_config"] = "Elegir config…",
                ["game_running"] = "Juego en ejecución",
                ["game_stopped"] = "Juego no iniciado",
                ["saved_live"] = "Guardado · recarga en vivo activa",
                ["saved_stopped"] = "Guardado · juego no iniciado",
                ["mod"] = "Mod",
                ["speed"] = "Velocidad",
                ["workshop"] = "Taller",
                ["training"] = "Formación",
                ["analysis"] = "Análisis",
                ["vet"] = "Veterinario",
                ["expeditions"] = "Expediciones",
                ["staff"] = "Personal",
                ["exhibit_extra_speed"] = "Extras de exposición",
                ["knowledge"] = "Conocimiento",
                ["analysis_max"] = "Análisis: conocimiento máximo tras un análisis",
                ["vet_max"] = "Veterinario: conocimiento máximo tras un tratamiento",
                ["applicants"] = "Candidatos",
                ["minimum_rank"] = "Rango mínimo",
                ["base_skill"] = "Conservar habilidad base vanilla y eliminar habilidades aleatorias adicionales",
                ["max_survey"] = "Exploración máxima tras una expedición",
                ["min_quality"] = "Calidad mínima",
                ["force_quality"] = "Forzar calidad exacta",
                ["security"] = "Seguridad",
                ["coverage_radius"] = "Radio de cobertura",
                ["health"] = "Salud",
                ["first_aid"] = "Los primeros auxilios curan enfermedades de expedición",
                ["preservation"] = "Conservación de exposiciones",
                ["preserve_exhibits"] = "Exposiciones: estado siempre al 100 %",
                ["immortal_plants"] = "Botánica: vida siempre al 100 %",
                ["aquariums_clean"] = "Acuarios: limpios + filtro 999",
                ["apply"] = "Aplicar",
                ["reload"] = "Recargar",
                ["vanilla"] = "Todo vanilla",
                ["start_game"] = "Iniciar juego",
                ["footer"] = "Los cambios se escriben en la config BepInEx existente y el mod los aplica en vivo.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normal",
                ["q_great"] = "Excelente",
                ["q_epic"] = "Épica",
                ["q_pristine"] = "Impecable",
                ["config_missing"] = "No se encontró TPMQoL.cfg. Selecciona manualmente el archivo de configuración.",
                ["load_error"] = "No se pudo cargar la configuración",
                ["save_error"] = "No se pudo guardar la configuración",
                ["start_error"] = "No se pudo iniciar el juego"
            },
            ["es-419"] = new()
            {
                ["language"] = "Idioma",
                ["choose_config"] = "Elegir config…",
                ["game_running"] = "Juego en ejecución",
                ["game_stopped"] = "Juego no iniciado",
                ["saved_live"] = "Guardado · recarga en vivo activa",
                ["saved_stopped"] = "Guardado · juego no iniciado",
                ["mod"] = "Mod",
                ["speed"] = "Velocidad",
                ["workshop"] = "Taller",
                ["training"] = "Capacitación",
                ["analysis"] = "Análisis",
                ["vet"] = "Veterinario",
                ["expeditions"] = "Expediciones",
                ["staff"] = "Personal",
                ["exhibit_extra_speed"] = "Extras de exposición",
                ["knowledge"] = "Conocimiento",
                ["analysis_max"] = "Análisis: conocimiento máximo después de un análisis",
                ["vet_max"] = "Veterinario: conocimiento máximo después de un tratamiento",
                ["applicants"] = "Candidatos",
                ["minimum_rank"] = "Rango mínimo",
                ["base_skill"] = "Conservar habilidad base vanilla y eliminar habilidades aleatorias adicionales",
                ["max_survey"] = "Exploración máxima después de una expedición",
                ["min_quality"] = "Calidad mínima",
                ["force_quality"] = "Forzar calidad exacta",
                ["security"] = "Seguridad",
                ["coverage_radius"] = "Radio de cobertura",
                ["health"] = "Salud",
                ["first_aid"] = "Los primeros auxilios curan enfermedades de expedición",
                ["preservation"] = "Conservación de exhibiciones",
                ["preserve_exhibits"] = "Exposiciones: estado siempre al 100 %",
                ["immortal_plants"] = "Botánica: vida siempre al 100 %",
                ["aquariums_clean"] = "Acuarios: limpios + filtro 999",
                ["apply"] = "Aplicar",
                ["reload"] = "Recargar",
                ["vanilla"] = "Todo vanilla",
                ["start_game"] = "Iniciar juego",
                ["footer"] = "Los cambios se escriben en la config BepInEx existente y el mod los aplica en vivo.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normal",
                ["q_great"] = "Excelente",
                ["q_epic"] = "Épica",
                ["q_pristine"] = "Impecable",
                ["config_missing"] = "No se encontró TPMQoL.cfg. Selecciona manualmente el archivo de configuración.",
                ["load_error"] = "No se pudo cargar la configuración",
                ["save_error"] = "No se pudo guardar la configuración",
                ["start_error"] = "No se pudo iniciar el juego"
            },
            ["pt-BR"] = new()
            {
                ["language"] = "Idioma",
                ["choose_config"] = "Escolher config…",
                ["game_running"] = "Jogo em execução",
                ["game_stopped"] = "Jogo não iniciado",
                ["saved_live"] = "Salvo · recarga ao vivo ativa",
                ["saved_stopped"] = "Salvo · jogo não iniciado",
                ["mod"] = "Mod",
                ["speed"] = "Velocidade",
                ["workshop"] = "Oficina",
                ["training"] = "Treinamento",
                ["analysis"] = "Análise",
                ["vet"] = "Veterinário",
                ["expeditions"] = "Expedições",
                ["staff"] = "Funcionários",
                ["exhibit_extra_speed"] = "Extras da exposição",
                ["knowledge"] = "Conhecimento",
                ["analysis_max"] = "Análise: conhecimento máximo após uma análise",
                ["vet_max"] = "Veterinário: conhecimento máximo após um tratamento",
                ["applicants"] = "Candidatos",
                ["minimum_rank"] = "Nível mínimo",
                ["base_skill"] = "Manter habilidade base vanilla e remover habilidades aleatórias extras",
                ["max_survey"] = "Exploração máxima após uma expedição",
                ["min_quality"] = "Qualidade mínima",
                ["force_quality"] = "Forçar qualidade exata",
                ["security"] = "Segurança",
                ["coverage_radius"] = "Raio de cobertura",
                ["health"] = "Saúde",
                ["first_aid"] = "Primeiros socorros curam doenças de expedição",
                ["preservation"] = "Preservação de exposições",
                ["preserve_exhibits"] = "Exposições: condição sempre em 100%",
                ["immortal_plants"] = "Botânica: vida sempre em 100%",
                ["aquariums_clean"] = "Aquários: limpos + filtro 999",
                ["apply"] = "Aplicar",
                ["reload"] = "Recarregar",
                ["vanilla"] = "Tudo vanilla",
                ["start_game"] = "Iniciar jogo",
                ["footer"] = "As alterações são gravadas na config BepInEx existente e aplicadas ao vivo pelo mod.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normal",
                ["q_great"] = "Ótima",
                ["q_epic"] = "Épica",
                ["q_pristine"] = "Impecável",
                ["config_missing"] = "TPMQoL.cfg não foi encontrado. Selecione o arquivo de configuração manualmente.",
                ["load_error"] = "Não foi possível carregar a configuração",
                ["save_error"] = "Não foi possível salvar a configuração",
                ["start_error"] = "Não foi possível iniciar o jogo"
            },
            ["tr"] = new()
            {
                ["language"] = "Dil",
                ["choose_config"] = "Yapılandırma seç…",
                ["game_running"] = "Oyun çalışıyor",
                ["game_stopped"] = "Oyun başlatılmadı",
                ["saved_live"] = "Kaydedildi · canlı yenileme etkin",
                ["saved_stopped"] = "Kaydedildi · oyun başlatılmadı",
                ["mod"] = "Mod",
                ["speed"] = "Hız",
                ["workshop"] = "Atölye",
                ["training"] = "Eğitim",
                ["analysis"] = "Analiz",
                ["vet"] = "Veteriner",
                ["expeditions"] = "Keşifler",
                ["staff"] = "Personel",
                ["exhibit_extra_speed"] = "Sergi ekstraları",
                ["knowledge"] = "Bilgi",
                ["analysis_max"] = "Analiz: bir analizden sonra maksimum bilgi",
                ["vet_max"] = "Veteriner: bir tedaviden sonra maksimum bilgi",
                ["applicants"] = "Adaylar",
                ["minimum_rank"] = "Minimum seviye",
                ["base_skill"] = "Vanilla temel yeteneği koru, ek rastgele yetenekleri kaldır",
                ["max_survey"] = "Bir keşiften sonra maksimum araştırma",
                ["min_quality"] = "Minimum kalite",
                ["force_quality"] = "Kesin kaliteyi zorla",
                ["security"] = "Güvenlik",
                ["coverage_radius"] = "Kapsama yarıçapı",
                ["health"] = "Sağlık",
                ["first_aid"] = "İlk yardım keşif hastalıklarını iyileştirir",
                ["preservation"] = "Sergi koruması",
                ["preserve_exhibits"] = "Sergiler: durum %100 kalır",
                ["immortal_plants"] = "Botanik: yaşam %100 kalır",
                ["aquariums_clean"] = "Akvaryumlar: temiz + filtre 999",
                ["apply"] = "Uygula",
                ["reload"] = "Yeniden yükle",
                ["vanilla"] = "Tümü vanilla",
                ["start_game"] = "Oyunu başlat",
                ["footer"] = "Değişiklikler mevcut BepInEx yapılandırmasına yazılır ve mod tarafından canlı uygulanır.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normal",
                ["q_great"] = "Harika",
                ["q_epic"] = "Destansı",
                ["q_pristine"] = "Kusursuz",
                ["config_missing"] = "TPMQoL.cfg bulunamadı. Yapılandırma dosyasını elle seçin.",
                ["load_error"] = "Yapılandırma yüklenemedi",
                ["save_error"] = "Yapılandırma kaydedilemedi",
                ["start_error"] = "Oyun başlatılamadı"
            },
            ["pl"] = new()
            {
                ["language"] = "Język",
                ["choose_config"] = "Wybierz konfigurację…",
                ["game_running"] = "Gra uruchomiona",
                ["game_stopped"] = "Gra nie jest uruchomiona",
                ["saved_live"] = "Zapisano · przeładowanie na żywo aktywne",
                ["saved_stopped"] = "Zapisano · gra nie jest uruchomiona",
                ["mod"] = "Mod",
                ["speed"] = "Szybkość",
                ["workshop"] = "Warsztat",
                ["training"] = "Szkolenie",
                ["analysis"] = "Analiza",
                ["vet"] = "Weterynarz",
                ["expeditions"] = "Ekspedycje",
                ["staff"] = "Personel",
                ["exhibit_extra_speed"] = "Dodatki eksponatu",
                ["knowledge"] = "Wiedza",
                ["analysis_max"] = "Analiza: maks. wiedza po jednej analizie",
                ["vet_max"] = "Weterynarz: maks. wiedza po jednym leczeniu",
                ["applicants"] = "Kandydaci",
                ["minimum_rank"] = "Minimalny poziom",
                ["base_skill"] = "Zachowaj bazową umiejętność vanilla, usuń dodatkowe losowe umiejętności",
                ["max_survey"] = "Maks. rozpoznanie po jednej ekspedycji",
                ["min_quality"] = "Minimalna jakość",
                ["force_quality"] = "Wymuś dokładną jakość",
                ["security"] = "Ochrona",
                ["coverage_radius"] = "Promień zasięgu",
                ["health"] = "Zdrowie",
                ["first_aid"] = "Pierwsza pomoc leczy choroby z ekspedycji",
                ["preservation"] = "Ochrona eksponatów",
                ["preserve_exhibits"] = "Eksponaty: stan pozostaje 100%",
                ["immortal_plants"] = "Botanika: życie pozostaje 100%",
                ["aquariums_clean"] = "Akwaria: czyste + filtr 999",
                ["apply"] = "Zastosuj",
                ["reload"] = "Wczytaj ponownie",
                ["vanilla"] = "Wszystko vanilla",
                ["start_game"] = "Uruchom grę",
                ["footer"] = "Zmiany są zapisywane w istniejącej konfiguracji BepInEx i stosowane na żywo przez mod.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Normalna",
                ["q_great"] = "Świetna",
                ["q_epic"] = "Epicka",
                ["q_pristine"] = "Doskonała",
                ["config_missing"] = "Nie znaleziono TPMQoL.cfg. Wybierz plik konfiguracji ręcznie.",
                ["load_error"] = "Nie udało się wczytać konfiguracji",
                ["save_error"] = "Nie udało się zapisać konfiguracji",
                ["start_error"] = "Nie udało się uruchomić gry"
            },
            ["ru"] = new()
            {
                ["language"] = "Язык",
                ["choose_config"] = "Выбрать конфиг…",
                ["game_running"] = "Игра запущена",
                ["game_stopped"] = "Игра не запущена",
                ["saved_live"] = "Сохранено · горячая перезагрузка активна",
                ["saved_stopped"] = "Сохранено · игра не запущена",
                ["mod"] = "Мод",
                ["speed"] = "Скорость",
                ["workshop"] = "Мастерская",
                ["training"] = "Обучение",
                ["analysis"] = "Анализ",
                ["vet"] = "Ветеринар",
                ["expeditions"] = "Экспедиции",
                ["staff"] = "Персонал",
                ["exhibit_extra_speed"] = "Дополнения экспоната",
                ["knowledge"] = "Знания",
                ["analysis_max"] = "Анализ: максимум знаний после одного анализа",
                ["vet_max"] = "Ветеринар: максимум знаний после одного лечения",
                ["applicants"] = "Кандидаты",
                ["minimum_rank"] = "Минимальный ранг",
                ["base_skill"] = "Сохранить базовый навык vanilla, удалить дополнительные случайные навыки",
                ["max_survey"] = "Максимум исследования после одной экспедиции",
                ["min_quality"] = "Минимальное качество",
                ["force_quality"] = "Принудительно точное качество",
                ["security"] = "Безопасность",
                ["coverage_radius"] = "Радиус покрытия",
                ["health"] = "Здоровье",
                ["first_aid"] = "Первая помощь лечит болезни экспедиций",
                ["preservation"] = "Сохранность экспонатов",
                ["preserve_exhibits"] = "Экспонаты: состояние остаётся 100%",
                ["immortal_plants"] = "Ботаника: жизнь остаётся 100%",
                ["aquariums_clean"] = "Аквариумы: чисто + фильтр 999",
                ["apply"] = "Применить",
                ["reload"] = "Перезагрузить",
                ["vanilla"] = "Всё vanilla",
                ["start_game"] = "Запустить игру",
                ["footer"] = "Изменения записываются в существующий конфиг BepInEx и применяются модом в реальном времени.",
                ["q_vanilla"] = "Vanilla",
                ["q_normal"] = "Обычное",
                ["q_great"] = "Отличное",
                ["q_epic"] = "Эпическое",
                ["q_pristine"] = "Безупречное",
                ["config_missing"] = "TPMQoL.cfg не найден. Выберите файл конфигурации вручную.",
                ["load_error"] = "Не удалось загрузить конфигурацию",
                ["save_error"] = "Не удалось сохранить конфигурацию",
                ["start_error"] = "Не удалось запустить игру"
            },
            ["ja"] = new()
            {
                ["language"] = "言語",
                ["choose_config"] = "設定ファイルを選択…",
                ["game_running"] = "ゲーム実行中",
                ["game_stopped"] = "ゲーム未起動",
                ["saved_live"] = "保存済み・ライブリロード有効",
                ["saved_stopped"] = "保存済み・ゲーム未起動",
                ["mod"] = "Mod",
                ["speed"] = "速度",
                ["workshop"] = "工房",
                ["training"] = "トレーニング",
                ["analysis"] = "分析",
                ["vet"] = "獣医",
                ["expeditions"] = "遠征",
                ["staff"] = "スタッフ",
                ["exhibit_extra_speed"] = "展示品の追加機能",
                ["knowledge"] = "知識",
                ["analysis_max"] = "分析：1回で知識を最大化",
                ["vet_max"] = "獣医：1回の治療で知識を最大化",
                ["applicants"] = "応募者",
                ["minimum_rank"] = "最低ランク",
                ["base_skill"] = "バニラの基本スキルを残し、追加ランダムスキルを削除",
                ["max_survey"] = "1回の遠征で調査を最大化",
                ["min_quality"] = "最低品質",
                ["force_quality"] = "品質を指定値に固定",
                ["security"] = "警備",
                ["coverage_radius"] = "監視範囲",
                ["health"] = "健康",
                ["first_aid"] = "応急処置で遠征病を治療",
                ["preservation"] = "展示物の保全",
                ["preserve_exhibits"] = "展示物：状態を100%に維持",
                ["immortal_plants"] = "植物展示：生命を100%に維持",
                ["aquariums_clean"] = "水槽：清潔維持 + フィルター999",
                ["apply"] = "適用",
                ["reload"] = "再読み込み",
                ["vanilla"] = "すべてバニラ",
                ["start_game"] = "ゲームを起動",
                ["footer"] = "変更は既存のBepInEx設定に書き込まれ、Modがライブで反映します。",
                ["q_vanilla"] = "バニラ",
                ["q_normal"] = "通常",
                ["q_great"] = "良好",
                ["q_epic"] = "エピック",
                ["q_pristine"] = "完璧",
                ["config_missing"] = "TPMQoL.cfgが見つかりません。設定ファイルを手動で選択してください。",
                ["load_error"] = "設定を読み込めませんでした",
                ["save_error"] = "設定を保存できませんでした",
                ["start_error"] = "ゲームを起動できませんでした"
            },
            ["ko"] = new()
            {
                ["language"] = "언어",
                ["choose_config"] = "설정 선택…",
                ["game_running"] = "게임 실행 중",
                ["game_stopped"] = "게임이 실행되지 않음",
                ["saved_live"] = "저장됨 · 실시간 다시 불러오기 활성",
                ["saved_stopped"] = "저장됨 · 게임이 실행되지 않음",
                ["mod"] = "Mod",
                ["speed"] = "속도",
                ["workshop"] = "작업실",
                ["training"] = "훈련",
                ["analysis"] = "분석",
                ["vet"] = "수의사",
                ["expeditions"] = "탐사",
                ["staff"] = "직원",
                ["exhibit_extra_speed"] = "전시품 추가 기능",
                ["knowledge"] = "지식",
                ["analysis_max"] = "분석: 1회 분석 후 지식 최대",
                ["vet_max"] = "수의사: 1회 치료 후 지식 최대",
                ["applicants"] = "지원자",
                ["minimum_rank"] = "최소 등급",
                ["base_skill"] = "바닐라 기본 스킬 유지, 추가 무작위 스킬 제거",
                ["max_survey"] = "1회 탐사 후 조사 최대",
                ["min_quality"] = "최소 품질",
                ["force_quality"] = "정확한 품질 강제",
                ["security"] = "보안",
                ["coverage_radius"] = "감시 반경",
                ["health"] = "건강",
                ["first_aid"] = "응급처치로 탐사 질병 치료",
                ["preservation"] = "전시물 보존",
                ["preserve_exhibits"] = "전시품: 상태 100% 유지",
                ["immortal_plants"] = "식물 전시: 생명 100% 유지",
                ["aquariums_clean"] = "수족관: 청결 유지 + 필터 999",
                ["apply"] = "적용",
                ["reload"] = "다시 불러오기",
                ["vanilla"] = "모두 바닐라",
                ["start_game"] = "게임 시작",
                ["footer"] = "변경 사항은 기존 BepInEx 설정에 기록되며 Mod가 실시간으로 적용합니다.",
                ["q_vanilla"] = "바닐라",
                ["q_normal"] = "보통",
                ["q_great"] = "훌륭함",
                ["q_epic"] = "에픽",
                ["q_pristine"] = "완벽함",
                ["config_missing"] = "TPMQoL.cfg를 찾을 수 없습니다. 설정 파일을 직접 선택하세요.",
                ["load_error"] = "설정을 불러올 수 없습니다",
                ["save_error"] = "설정을 저장할 수 없습니다",
                ["start_error"] = "게임을 시작할 수 없습니다"
            },
            ["zh-CN"] = new()
            {
                ["language"] = "语言",
                ["choose_config"] = "选择配置…",
                ["game_running"] = "游戏运行中",
                ["game_stopped"] = "游戏未启动",
                ["saved_live"] = "已保存 · 实时重载已启用",
                ["saved_stopped"] = "已保存 · 游戏未启动",
                ["mod"] = "Mod",
                ["speed"] = "速度",
                ["workshop"] = "工坊",
                ["training"] = "培训",
                ["analysis"] = "分析",
                ["vet"] = "兽医",
                ["expeditions"] = "探险",
                ["staff"] = "员工",
                ["exhibit_extra_speed"] = "展品附加项",
                ["knowledge"] = "知识",
                ["analysis_max"] = "分析：一次分析后知识最大",
                ["vet_max"] = "兽医：一次治疗后知识最大",
                ["applicants"] = "应聘者",
                ["minimum_rank"] = "最低等级",
                ["base_skill"] = "保留原版基础技能，移除额外随机技能",
                ["max_survey"] = "一次探险后调查最大",
                ["min_quality"] = "最低品质",
                ["force_quality"] = "强制精确品质",
                ["security"] = "安保",
                ["coverage_radius"] = "监控半径",
                ["health"] = "健康",
                ["first_aid"] = "急救可治疗探险疾病",
                ["preservation"] = "展品维护",
                ["preserve_exhibits"] = "展品：状态保持 100%",
                ["immortal_plants"] = "植物展品：生命保持 100%",
                ["aquariums_clean"] = "水族箱：保持清洁 + 过滤器 999",
                ["apply"] = "应用",
                ["reload"] = "重新加载",
                ["vanilla"] = "全部原版",
                ["start_game"] = "启动游戏",
                ["footer"] = "更改会写入现有 BepInEx 配置，并由 Mod 实时应用。",
                ["q_vanilla"] = "原版",
                ["q_normal"] = "普通",
                ["q_great"] = "优秀",
                ["q_epic"] = "史诗",
                ["q_pristine"] = "完美",
                ["config_missing"] = "未找到 TPMQoL.cfg。请手动选择配置文件。",
                ["load_error"] = "无法加载配置",
                ["save_error"] = "无法保存配置",
                ["start_error"] = "无法启动游戏"
            },
            ["zh-TW"] = new()
            {
                ["language"] = "語言",
                ["choose_config"] = "選擇設定…",
                ["game_running"] = "遊戲執行中",
                ["game_stopped"] = "遊戲未啟動",
                ["saved_live"] = "已儲存 · 即時重新載入已啟用",
                ["saved_stopped"] = "已儲存 · 遊戲未啟動",
                ["mod"] = "Mod",
                ["speed"] = "速度",
                ["workshop"] = "工坊",
                ["training"] = "訓練",
                ["analysis"] = "分析",
                ["vet"] = "獸醫",
                ["expeditions"] = "探險",
                ["staff"] = "員工",
                ["exhibit_extra_speed"] = "展品附加項",
                ["knowledge"] = "知識",
                ["analysis_max"] = "分析：一次分析後知識最大",
                ["vet_max"] = "獸醫：一次治療後知識最大",
                ["applicants"] = "應徵者",
                ["minimum_rank"] = "最低等級",
                ["base_skill"] = "保留原版基礎技能，移除額外隨機技能",
                ["max_survey"] = "一次探險後調查最大",
                ["min_quality"] = "最低品質",
                ["force_quality"] = "強制精確品質",
                ["security"] = "保全",
                ["coverage_radius"] = "監控半徑",
                ["health"] = "健康",
                ["first_aid"] = "急救可治療探險疾病",
                ["preservation"] = "展品維護",
                ["preserve_exhibits"] = "展品：狀態保持 100%",
                ["immortal_plants"] = "植物展品：生命保持 100%",
                ["aquariums_clean"] = "水族箱：保持清潔 + 過濾器 999",
                ["apply"] = "套用",
                ["reload"] = "重新載入",
                ["vanilla"] = "全部原版",
                ["start_game"] = "啟動遊戲",
                ["footer"] = "變更會寫入現有 BepInEx 設定，並由 Mod 即時套用。",
                ["q_vanilla"] = "原版",
                ["q_normal"] = "普通",
                ["q_great"] = "優秀",
                ["q_epic"] = "史詩",
                ["q_pristine"] = "完美",
                ["config_missing"] = "找不到 TPMQoL.cfg。請手動選擇設定檔。",
                ["load_error"] = "無法載入設定",
                ["save_error"] = "無法儲存設定",
                ["start_error"] = "無法啟動遊戲"
            },
            ["th"] = new()
            {
                ["language"] = "ภาษา",
                ["choose_config"] = "เลือกไฟล์ตั้งค่า…",
                ["game_running"] = "เกมกำลังทำงาน",
                ["game_stopped"] = "เกมยังไม่เริ่ม",
                ["saved_live"] = "บันทึกแล้ว · โหลดสดทำงาน",
                ["saved_stopped"] = "บันทึกแล้ว · เกมยังไม่เริ่ม",
                ["mod"] = "Mod",
                ["speed"] = "ความเร็ว",
                ["workshop"] = "เวิร์กช็อป",
                ["training"] = "การฝึก",
                ["analysis"] = "การวิเคราะห์",
                ["vet"] = "สัตวแพทย์",
                ["expeditions"] = "การสำรวจ",
                ["staff"] = "พนักงาน",
                ["exhibit_extra_speed"] = "ส่วนเสริมจัดแสดง",
                ["knowledge"] = "ความรู้",
                ["analysis_max"] = "วิเคราะห์: ความรู้สูงสุดหลังวิเคราะห์หนึ่งครั้ง",
                ["vet_max"] = "สัตวแพทย์: ความรู้สูงสุดหลังรักษาหนึ่งครั้ง",
                ["applicants"] = "ผู้สมัคร",
                ["minimum_rank"] = "ระดับขั้นต่ำ",
                ["base_skill"] = "เก็บสกิลพื้นฐานแบบวานิลลาและลบสกิลสุ่มเพิ่มเติม",
                ["max_survey"] = "สำรวจสูงสุดหลังการสำรวจหนึ่งครั้ง",
                ["min_quality"] = "คุณภาพขั้นต่ำ",
                ["force_quality"] = "บังคับคุณภาพที่กำหนด",
                ["security"] = "ความปลอดภัย",
                ["coverage_radius"] = "รัศมีการครอบคลุม",
                ["health"] = "สุขภาพ",
                ["first_aid"] = "ปฐมพยาบาลรักษาโรคจากการสำรวจ",
                ["preservation"] = "การรักษาสภาพนิทรรศการ",
                ["preserve_exhibits"] = "นิทรรศการ: สภาพคงที่ 100%",
                ["immortal_plants"] = "พฤกษศาสตร์: ชีวิตคงที่ 100%",
                ["aquariums_clean"] = "ตู้ปลา: สะอาด + ตัวกรอง 999",
                ["apply"] = "ใช้",
                ["reload"] = "โหลดใหม่",
                ["vanilla"] = "ทั้งหมดแบบวานิลลา",
                ["start_game"] = "เริ่มเกม",
                ["footer"] = "การเปลี่ยนแปลงจะถูกเขียนลงใน BepInEx config เดิมและ Mod จะนำไปใช้แบบสด",
                ["q_vanilla"] = "วานิลลา",
                ["q_normal"] = "ปกติ",
                ["q_great"] = "ยอดเยี่ยม",
                ["q_epic"] = "มหากาพย์",
                ["q_pristine"] = "สมบูรณ์แบบ",
                ["config_missing"] = "ไม่พบ TPMQoL.cfg กรุณาเลือกไฟล์ตั้งค่าด้วยตนเอง",
                ["load_error"] = "ไม่สามารถโหลดการตั้งค่าได้",
                ["save_error"] = "ไม่สามารถบันทึกการตั้งค่าได้",
                ["start_error"] = "ไม่สามารถเริ่มเกมได้"
            }
        };

    internal static string CurrentCode { get; private set; } = "en";

    internal static void SetLanguage(string code)
    {
        CurrentCode = Data.ContainsKey(code) ? code : "en";
    }

    internal static string T(string key)
    {
        if (Data.TryGetValue(CurrentCode, out var selected) && selected.TryGetValue(key, out var text))
            return text;

        if (Data["en"].TryGetValue(key, out var fallback))
            return fallback;

        return key;
    }

    internal static string DetectLanguage()
    {
        var name = CultureInfo.CurrentUICulture.Name;
        var two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;

        if (name.StartsWith("zh-Hant", StringComparison.OrdinalIgnoreCase) ||
            name.StartsWith("zh-TW", StringComparison.OrdinalIgnoreCase) ||
            name.StartsWith("zh-HK", StringComparison.OrdinalIgnoreCase) ||
            name.StartsWith("zh-MO", StringComparison.OrdinalIgnoreCase))
            return "zh-TW";

        if (two.Equals("zh", StringComparison.OrdinalIgnoreCase))
            return "zh-CN";

        if (two.Equals("es", StringComparison.OrdinalIgnoreCase))
            return name.Equals("es-ES", StringComparison.OrdinalIgnoreCase) ? "es-ES" : "es-419";

        if (two.Equals("pt", StringComparison.OrdinalIgnoreCase))
            return "pt-BR";

        var match = Languages.FirstOrDefault(x =>
            x.Code.Equals(two, StringComparison.OrdinalIgnoreCase) ||
            x.Code.Equals(name, StringComparison.OrdinalIgnoreCase));

        return match?.Code ?? "en";
    }
}
