<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>TPMQoLTrainer</AssemblyName>
    <RootNamespace>TPMQoLTrainer</RootNamespace>
    <Version>1.0.2</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Payload\TPMQoL.dll" LogicalName="TPMQoL.Payload.TPMQoL.dll" />
  </ItemGroup>
</Project>
